import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Link from 'next/link';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { status } = useSession();

  const { data: watchlist } = trpc.useQuery(['watchlist.get-all'], {
    enabled: status !== 'unauthenticated',
  });

  return (
    <>
      <Head>
        <title>Snapstock</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {watchlist?.map((stock) => (
          <Link href={`/quotes/${stock.symbol}`} key={stock.symbol}>
            <li className="link">
              {stock.symbol} - {stock.companyName}
            </li>
          </Link>
        ))}
      </ul>
    </>
  );
};

export default Home;
